### ISSUE TITLE
browsermob proxy not working on Rancher

### ISSUE THREAD

**Issue by mackost** [lightbody/browsermob-proxy#821]
Hi, this is the content of my docker-compose file:

```
  hub:
    image: selenium/hub
    environment:
      GRID_DEBUG: "true"
      GRID_TIMEOUT: 60
      GRID_MAX_SESSION: 8
      SE_OPTS: -port 4445
    tty: true


  chrome:
    image: selenium/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      HUB_PORT: 4445
      NODE_MAX_INSTANCES: 4
      NODE_MAX_SESSION: 4
      SCREEN_HEIGHT: 1080
      SCREEN_WIDTH: 1920

  browsermobproxy:
    image:  bwowk/browsermob-proxy
    container_name: browsermobproxy
    depends_on:
      - hub
    environment:
      BMP_PORT: 9090
```

When I run that on my computer everything work as expected, but the problem is when I try to set it up on Rancher platform the proxy doesn't work.

Here are the logs :
#### Hub:
```
23/05/2019 10:27:4608:27:46.486 INFO [ActiveSessionFactory.apply] - Capabilities are: {
23/05/2019 10:27:46  "browserName": "chrome",
23/05/2019 10:27:46  "browserTimeout": 300,
23/05/2019 10:27:46  "browser_version": "70.0.3538.102",
23/05/2019 10:27:46  "goog:chromeOptions": {
23/05/2019 10:27:46    "args": [
23/05/2019 10:27:46      "--disable-notifications"
23/05/2019 10:27:46    ],
23/05/2019 10:27:46    "extensions": [
23/05/2019 10:27:46    ]
23/05/2019 10:27:46  },
23/05/2019 10:27:46  "idleTimeout": 300,
23/05/2019 10:27:46  "os": "",
23/05/2019 10:27:46  "os_version": "",
23/05/2019 10:27:46  "proxy": {
23/05/2019 10:27:46    "httpProxy": "browsermobproxy:39504",
23/05/2019 10:27:46    "proxyType": "manual",
23/05/2019 10:27:46    "sslProxy": "browsermobproxy:39504"
23/05/2019 10:27:46  },
23/05/2019 10:27:46  "screenResolution": "1920x1080",
23/05/2019 10:27:46  "version": ""
23/05/2019 10:27:46}
23/05/2019 10:27:4608:27:46.486 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.grid.session.remote.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
23/05/2019 10:27:46Starting ChromeDriver 74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}) on port 29641
23/05/2019 10:27:46Only local connections are allowed.
23/05/2019 10:27:46Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
23/05/2019 10:27:4608:27:46.887 INFO [ProtocolHandshake.createSession] - Detected dialect: OSS
23/05/2019 10:27:4608:27:46.897 INFO [RemoteSession$Factory.lambda$performHandshake$0] - Started new session 6709c1cdabfd4dea55ccf36ec2a2f5ed (org.openqa.selenium.chrome.ChromeDriverService)
```

#### Chrome:
```
23/05/2019 10:27:4608:27:46.478 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: chrome, browserTimeout: 300, browser_version: 70.0.3538.102, goog:chromeOptions: {args: [--disable-notifications], extensions: []}, idleTimeout: 300, os: , os_version: , proxy: {httpProxy: browsermobproxy:39504, proxyType: manual, sslProxy: browsermobproxy:39504}, screenResolution: 1920x1080, version: }
23/05/2019 10:27:4608:27:46.478 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=c0ec1c73-3fc7-4012-97b6-1df56269aea7, seleniumProtocol=WebDriver, browserName=chrome, maxInstances=32, platformName=LINUX, version=74.0.3729.108, applicationName=, platform=LINUX}
```

#### Proxy:
```
23/05/2019 10:27:46[INFO  2019-05-23T08:27:46,466 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp2053628870-18) Starting proxy at address: 0.0.0.0/0.0.0.0:39504
23/05/2019 10:27:46[INFO  2019-05-23T08:27:46,468 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp2053628870-18) Proxy listening with TCP transport
23/05/2019 10:27:46[INFO  2019-05-23T08:27:46,470 org.littleshoot.proxy.impl.DefaultHttpProxyServer] (qtp2053628870-18) Proxy started at address: /0:0:0:0:0:0:0:0:39504
```

Any ideas?
